apiVersion: v1
kind: Pod
metadata:
  name: buildah-pod
spec:
  containers:
  - name: buildah
    image: quay.io/buildah/stable
    command: ["/bin/sh"]
    args:
      - "-c"
      - |
        newcontainer=$(buildah from scratch); \
        if [ -f /mnt/checkpoints/checkpoint-redis12.tar ]; then \
          buildah add $newcontainer /mnt/checkpoints/checkpoint-redis12.tar /; \
          buildah config --annotation=io.kubernetes.cri-o.annotations.checkpoint.name=migration-sample $newcontainer; \
          buildah commit $newcontainer  newcontainer:latest; \
          buildah rm $newcontainer; \
          sleep 100000; \
        else \
          echo "File not found"; \
          exit 1; \
        fi
    volumeMounts:
    - mountPath: /mnt/checkpoints #src node
      name: checkpoint-storage
    - mountPath: /var/lib/containers/storage # the following mountpath settings are for destination node
      name: container-storage-graphroot
    - mountPath: /run/containers/storage
      name: container-storage-runroot
    - mountPath: /etc/containers/storage.conf
      name: container-storage-conf
    - mountPath: /etc/containers/policy.json
      name: container-policy
    
    securityContext:
      privileged: true 
      runAsUser: 0
      runAsGroup: 0

  volumes:
  - name: checkpoint-storage
    persistentVolumeClaim:
      claimName: pvc-nfs
  - name: container-storage-graphroot
    hostPath:
      path: /var/lib/containers/storage
  - name: container-storage-runroot
    hostPath:
      path: /run/containers/storage
  - name: container-storage-conf
    hostPath:
      path: /etc/containers/storage.conf
  - name: container-policy
    hostPath:
      path: /etc/containers/policy.json
  restartPolicy: Always
