# ServiceAccount in the practice-system namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-list-sa
  namespace: practice-system
---
# Role to list and get custom resources and events in the practice-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: practice-system
  name: event-list-role
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["api.my.domain"]
  resources: ["migrations"]
  verbs: ["list", "get", "watch"]
---
# RoleBinding to bind the Role to the ServiceAccount in the practice-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-list-rolebinding
  namespace: practice-system
subjects:
- kind: ServiceAccount
  name: event-list-sa
  namespace: practice-system
roleRef:
  kind: Role
  name: event-list-role
  apiGroup: rbac.authorization.k8s.io
---
# Pod in the practice-system namespace
apiVersion: v1
kind: Pod
metadata:
  name: benchmark
  namespace: practice-system
spec:
  serviceAccountName: event-list-sa
  containers:
  - name: benchmark
    image: tonyliu666/benchmark:latest
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
