apiVersion: v1 
kind: Pod 
metadata: 
  name: httpd
  namespace: default
spec:
  containers:
  - name: httpd
    image: httpd:latest
    ports:
      - containerPort: 80
  imagePullSecrets:
    - name: regcred
  nodeName: workernode01

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: httpd-service
# spec:
#   selector:
#     app: httpd
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80