apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: docker-registry
type: Opaque
data:
  # Base64 encoded string of 'myuser:$2y$05$SC5AAIwwjc54t4h4XQEFXey5a5xEkdH6sR7SiwzSTRqvVpa6R2HbW'
  REGISTRY_HTTP_SECRET: bXl1c2VyOiQyeSQwNSRTQzVBQUl3d2pjNTR0NGg0WFFFRlhleTVhNXhFa2RINnNSN1Npd3pTVFJxdlZwYTZSMkhkYlc=