apiVersion: v1 
kind: Pod
metadata:
  name: mongodb2
  namespace: default
spec:
  containers:
  - name: mongodb2
    image: mongo:latest
  # imagePullSecrets:
  #   - name: regcred
  nodeName: workernode02
