apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
  namespace: default
  labels:
    app: jupyter
spec:
  containers:
  - name: jupyter-container
    image: jupyter/datascience-notebook:latest
    ports:
    - containerPort: 8888
      name: jupyter
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    args: [
      "start-notebook.sh",
      "--NotebookApp.token=''",
      "--ip='0.0.0.0'",
      "--port=8888",
      "--no-browser"
    ]
  restartPolicy: OnFailure